apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatserver-deployment
  labels:
    app: chatserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatserver
  template:
    metadata:
      labels:
        app: chatserver
    spec:
      containers:
      - name: chatserver
        image: mallington/chatsystem:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
