# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8.0
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Build docker image
      run: docker build ./ -t mallington/chatsystem:1.0.0
      
    - name: Docker push
      run: docker push mallington/chatsystem:1.0.0
    
    - name: Archive latest jar
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
